[dependencies]

[dependencies.A]
versions = [ "1.2", "1.5", "2", "1", "5.3", "2.4" ]
hints = [ ">=1.2.5", "<=6.3.2" ]
depends = [ "B", "C" ]

[dependencies.B]
versions = [ "1.2", "3.1", "5.3", "2.71" ]
hints = [ "==1.2.9" ]
depends = []

[dependencies.C]
versions = [ "1.546.3", "2.4.7.3.7", "901.123.4357.7" ]
hints = [ "!=2.5.35.4" ]
depends = [ "A" ]

[[tests]]

[[tests.true_when]]
A = [ "1.9", "4.0.0.0" ]
B = [ "2.70", "3.1" ]
C = [ "1", "1" ]

[[tests.true_when]]
A = [ "1.9", "2.0.0.0" ]
C = [ "2", "2" ]

[[tests.true_when]]
A = [ "1.9", "3.3.2" ]
B = [ "2.70", "3.1" ]
C = [ "1", "1.5" ]

[[tests]]

[[tests.true_when]]
C = [ "2", "4" ]

