[dependencies]

[dependencies.A]
versions = [ "1.2", "1.5", "2", "1", "5.3", "2.4" ]
specifier = ">=1.2.5,<=6.3.2"

[dependencies.B]
versions = [ "1.2", "1.2.9", "3.1", "5.3", "2.71" ]
specifier = ">=1.2.9"

[dependencies.C]
versions = [ "1.546.3", "2.4.7.3.7", "901.123.4357.7" ]
specifier = "!=2.5.35.4"

[[tests]]

[[tests.true_when]]
A = [ "1.9", "4.0.0.0" ]
B = [ "2.70", "3.1" ]
C = [ "1", "1" ]

[[tests.true_when]]
A = [ "1.9", "2.0.0.0" ]
C = [ "2", "2" ]

[[tests.true_when]]
A = [ "1.9", "3.3.2" ]
B = [ "2.70", "3.1" ]
C = [ "1", "2" ]

[[tests]]

[[tests.true_when]]
A = [ "0", "400" ]
B = [ "0", "400" ]
C = [ "0", "400" ]

